"""Type stubs for Blender's ``mathutils`` module.

``mathutils`` is a C extension that Blender (and the pip ``bpy`` package)
injects into ``sys.modules`` at runtime; it has no source on disk, so static
analysers such as PyCharm cannot resolve names like ``Vector`` or
``Quaternion`` and flag every import of them as red.

This stub exists purely so the IDE can resolve those names. CPython never
imports ``.pyi`` files, so it cannot shadow the real builtin at runtime — only
the IDE / type checker reads it. Keep it light; extend as needed.
"""

from __future__ import annotations

from typing import Any, Iterator, Sequence, overload

_Number = float | int
_VectorLike = "Vector | Sequence[_Number]"


class Vector:
    x: float
    y: float
    z: float
    w: float
    length: float
    length_squared: float
    magnitude: float
    is_frozen: bool
    is_wrapped: bool

    def __init__(self, seq: Sequence[_Number] = ...) -> None: ...
    @classmethod
    def Fill(cls, size: int, fill: _Number = ...) -> "Vector": ...
    @classmethod
    def Range(cls, start: int = ..., stop: int = ..., step: int = ...) -> "Vector": ...
    @classmethod
    def Linspace(cls, start: _Number, stop: _Number, size: int) -> "Vector": ...
    @classmethod
    def Repeat(cls, vector: "Vector", size: int) -> "Vector": ...

    def normalize(self) -> None: ...
    def normalized(self) -> "Vector": ...
    def dot(self, other: "Vector") -> float: ...
    def cross(self, other: "Vector") -> "Vector": ...
    def angle(self, other: "Vector", fallback: Any = ...) -> float: ...
    def angle_signed(self, other: "Vector", fallback: Any = ...) -> float: ...
    def rotation_difference(self, other: "Vector") -> "Quaternion": ...
    def reflect(self, mirror: "Vector") -> "Vector": ...
    def project(self, other: "Vector") -> "Vector": ...
    def lerp(self, other: "Vector", factor: _Number) -> "Vector": ...
    def slerp(self, other: "Vector", factor: _Number, fallback: Any = ...) -> "Vector": ...
    def rotate(self, other: "Euler | Quaternion | Matrix") -> None: ...
    def resize(self, size: int) -> None: ...
    def resized(self, size: int) -> "Vector": ...
    def to_2d(self) -> "Vector": ...
    def to_3d(self) -> "Vector": ...
    def to_4d(self) -> "Vector": ...
    def to_tuple(self, precision: int = ...) -> tuple[float, ...]: ...
    def to_track_quat(self, track: str, up: str) -> "Quaternion": ...
    def copy(self) -> "Vector": ...
    def freeze(self) -> "Vector": ...

    @property
    def xy(self) -> "Vector": ...
    @property
    def xyz(self) -> "Vector": ...
    @property
    def xyzw(self) -> "Vector": ...

    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[float]: ...
    def __getitem__(self, key: int) -> float: ...
    def __setitem__(self, key: int, value: _Number) -> None: ...
    def __add__(self, other: "Vector") -> "Vector": ...
    def __sub__(self, other: "Vector") -> "Vector": ...
    def __mul__(self, other: "_Number | Vector | Matrix") -> "Vector | float": ...
    def __rmul__(self, other: "_Number | Matrix") -> "Vector": ...
    def __truediv__(self, other: _Number) -> "Vector": ...
    def __matmul__(self, other: "Vector | Matrix") -> "Vector | float": ...
    def __neg__(self) -> "Vector": ...


class Quaternion:
    w: float
    x: float
    y: float
    z: float
    angle: float
    axis: Vector
    magnitude: float
    is_frozen: bool
    is_wrapped: bool

    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, seq: Sequence[_Number]) -> None: ...
    @overload
    def __init__(self, axis: "Vector | Sequence[_Number]", angle: _Number) -> None: ...

    def normalize(self) -> None: ...
    def normalized(self) -> "Quaternion": ...
    def invert(self) -> None: ...
    def inverted(self) -> "Quaternion": ...
    def conjugate(self) -> None: ...
    def conjugated(self) -> "Quaternion": ...
    def dot(self, other: "Quaternion") -> float: ...
    def cross(self, other: "Quaternion") -> "Quaternion": ...
    def rotate(self, other: "Euler | Quaternion | Matrix") -> None: ...
    def rotation_difference(self, other: "Quaternion") -> "Quaternion": ...
    def slerp(self, other: "Quaternion", factor: _Number) -> "Quaternion": ...
    def to_euler(self, order: str = ..., euler_compat: "Euler" = ...) -> "Euler": ...
    def to_matrix(self) -> "Matrix": ...
    def to_axis_angle(self) -> tuple[Vector, float]: ...
    def to_exponential_map(self) -> Vector: ...
    def make_compatible(self, other: "Quaternion") -> None: ...
    def copy(self) -> "Quaternion": ...
    def freeze(self) -> "Quaternion": ...

    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[float]: ...
    def __getitem__(self, key: int) -> float: ...
    def __setitem__(self, key: int, value: _Number) -> None: ...
    def __mul__(self, other: "Quaternion | _Number") -> "Quaternion": ...
    def __matmul__(self, other: "Quaternion | Vector") -> "Quaternion | Vector": ...
    def __add__(self, other: "Quaternion") -> "Quaternion": ...
    def __sub__(self, other: "Quaternion") -> "Quaternion": ...


class Euler:
    x: float
    y: float
    z: float
    order: str
    is_frozen: bool
    is_wrapped: bool

    def __init__(self, angles: Sequence[_Number] = ..., order: str = ...) -> None: ...
    def to_matrix(self) -> "Matrix": ...
    def to_quaternion(self) -> "Quaternion": ...
    def rotate(self, other: "Euler | Quaternion | Matrix") -> None: ...
    def rotate_axis(self, axis: str, angle: _Number) -> None: ...
    def make_compatible(self, other: "Euler") -> None: ...
    def copy(self) -> "Euler": ...
    def freeze(self) -> "Euler": ...

    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[float]: ...
    def __getitem__(self, key: int) -> float: ...
    def __setitem__(self, key: int, value: _Number) -> None: ...


class Matrix:
    is_frozen: bool
    is_wrapped: bool
    is_negative: bool
    is_orthogonal: bool
    median_scale: float
    translation: Vector

    def __init__(self, rows: Sequence[Sequence[_Number]] = ...) -> None: ...
    @classmethod
    def Identity(cls, size: int) -> "Matrix": ...
    @classmethod
    def Rotation(cls, angle: _Number, size: int, axis: "str | Vector" = ...) -> "Matrix": ...
    @classmethod
    def Scale(cls, factor: _Number, size: int, axis: "Vector" = ...) -> "Matrix": ...
    @classmethod
    def Translation(cls, vector: "Vector | Sequence[_Number]") -> "Matrix": ...
    @classmethod
    def Diagonal(cls, vector: "Vector | Sequence[_Number]") -> "Matrix": ...
    @classmethod
    def OrthoProjection(cls, axis: "str | Vector", size: int) -> "Matrix": ...

    def normalize(self) -> None: ...
    def normalized(self) -> "Matrix": ...
    def invert(self, fallback: "Matrix" = ...) -> None: ...
    def inverted(self, fallback: Any = ...) -> "Matrix": ...
    def inverted_safe(self) -> "Matrix": ...
    def transpose(self) -> None: ...
    def transposed(self) -> "Matrix": ...
    def determinant(self) -> float: ...
    def decompose(self) -> tuple[Vector, Quaternion, Vector]: ...
    def to_3x3(self) -> "Matrix": ...
    def to_4x4(self) -> "Matrix": ...
    def to_euler(self, order: str = ..., euler_compat: "Euler" = ...) -> "Euler": ...
    def to_quaternion(self) -> "Quaternion": ...
    def to_scale(self) -> Vector: ...
    def to_translation(self) -> Vector: ...
    def copy(self) -> "Matrix": ...
    def freeze(self) -> "Matrix": ...

    @property
    def row(self) -> Any: ...
    @property
    def col(self) -> Any: ...

    def __getitem__(self, key: int) -> Vector: ...
    def __setitem__(self, key: int, value: "Vector | Sequence[_Number]") -> None: ...
    def __iter__(self) -> Iterator[Vector]: ...
    def __len__(self) -> int: ...
    def __matmul__(self, other: "Matrix | Vector") -> "Matrix | Vector": ...
    def __mul__(self, other: "Matrix | Vector | _Number") -> "Matrix | Vector": ...


class Color:
    r: float
    g: float
    b: float
    h: float
    s: float
    v: float
    hsv: tuple[float, float, float]
    is_frozen: bool
    is_wrapped: bool

    def __init__(self, rgb: Sequence[_Number] = ...) -> None: ...
    def copy(self) -> "Color": ...
    def freeze(self) -> "Color": ...
    def from_scene_linear_to_srgb(self) -> "Color": ...
    def from_srgb_to_scene_linear(self) -> "Color": ...

    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[float]: ...
    def __getitem__(self, key: int) -> float: ...
    def __setitem__(self, key: int, value: _Number) -> None: ...
